# Generated by Django 4.1.7 on 2023-02-15 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=3)),
                ('weekday', models.CharField(max_length=5)),
                ('is_holiday', models.BooleanField(default=False)),
                ('remarks', models.CharField(max_length=255)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_year_day', to='holiday.calendaryear')),
            ],
        ),
    ]
